# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Burak Aksar
title: PhD Candidate
email: baksar@bu.edu
website: https://aksarburak.github.io/burakaksar.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: skyraxai
github_username:  aksarburak
linkedin_username: burakaksar
orcid_username: 0000-0003-3627-7311

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, this is Burak. I am a PhD candidate at Boston University, working under the supervision of Prof. Ayse Coskun 
  in [PeacLab](https://www.bu.edu/peaclab/) research group.  

content:

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        # title: Super awesome project
        # link: github.com/sproogen        
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme

        description: | # this will include new lines to allow paragraphs        

          [1] **Burak Aksar**, Yara Rizk, Tathagata Chakraborti, Kartik Talamadupula. TESS: A Multi‑intent Parser for Conversational Multi‑Agent Systems with Decentralized Natural Language Understanding Models”. Submitted to ACL 2023.

          [2] Tathagata Chakraborti, Yara Rizk, Vatche Isahagian, **Burak Aksar**, Francesco Fuggitti. From Natural Language to Workflows: Towards Emergent Intelligence in Robotic Process Automation. In International Conference on Business Process Management (BPM), July 2022. icon: fab fa-github

          [3] **Burak Aksar**, Efe Sencan, Benjamin Schwaller, Omar Aaziz, Vitus J. Leung, Jim Brandt, Brian Kulis, and Ayse K. Coskun. ALBADross: Active Learning Based Anomaly Diagnosis for Production HPC Systems . In IEEE International Conference on Cluster Computing (Cluster) , July 2022. [Code](https://github.com/peaclab/ALBADross)

          [4] Yijia Zhang, **Burak Aksar**, Omar Aaziz, Benjamin Schwaller, Jim Brandt, Vitus J. Leung, Manuel Egele, and Ayse K. Coskun. Using Monitoring Data to Improve HPC Performance via Network-Data-Driven Allocation. In High Performance Extreme Computing Conference (HPEC), Sept. 2021.

          [5] Burak Aksar, Benjamin Schwaller, Omar Aaziz, Vitus J. Leung, Jim Brandt, Manuel Egele, and Ayse K. Coskun. E2EWatch: An End-to-end Anomaly Diagnosis Framework for Production HPC Systems. In International European Conference on Parallel and Distributed Computing (Euro-Par), August 2021. [Code](https://github.com/peaclab/E2EWatch)

          [6] **Burak Aksar**, Yijia Zhang , Emre Ates, Benjamin Schwaller, Omar Aaziz, Vitus J. Leung, Jim Brandt, Manuel Egele, and Ayse K. Coskun. Proctor: A Semi-Supervised Performance Anomaly Diagnosis Framework for Production HPC Systems. In International Supercomputing Conference (ISC-HPC), June 2021. [Code](https://github.com/peaclab/Proctor)

          [7] Emre Ates, **Burak Aksar**, Vitus J. Leung, and Ayse K. Coskun. Counterfactual Explanations for Multivariate Time Series. In Proceedings of IEEE International Conference on Applied Artifical Intelligence (ICAPAI), May 2021. [Code](https://github.com/peaclab/CoMTE)

          [8] Emre Ates, Yijia Zhang, Burak Aksar, Jim Brandt, Vitus J. Leung, Manuel Egele, and Ayse K. Coskun. HPAS: An HPC Performance Anomaly Suite for Reproducing Performance Variations. In International Conference on Parallel Processing (ICPP 2019), pp. 1-10, Aug. 2019. [Code](https://github.com/peaclab/HPAS)


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IBM AI Research
        sub_title: Research Scientist Intern
        caption: May 2022 - Aug. 2022
        description: | # this will include new lines to allow paragraphs        
          - Researched the NLP explainability techniques for conversational multi‑agent systems (CMAS)

          - Evaluated existing NLP explainability frameworks and prototyped a new framework for a CMAS
  
      - layout: left
        title: IBM AI Research
        sub_title: Research Scientist Intern
        caption: June 2021 - Sept. 2021
        description: | # this will include new lines to allow paragraphs                  
          - Developed a multi-intent classification algorithm with a heuristic parser and natural language understanding models for a multi-chatbot system

          - Conducted tests and deployed the parser to the production pipeline

      - layout: left
        title: Sandia National Labs
        sub_title: Machine Learning SDE Intern
        caption: July 2020 - Sept. 2020
        description: | # this will include new lines to allow paragraphs                  
          - Designed and developed an ML pipeline for run-time performance anomaly detection

          - Deployed the pipeline to a production computing cluster with 1,488 nodes

      - layout: left
        title: Sandia National Labs
        sub_title: Machine Learning Research Intern
        caption: May 2019 - Aug. 2019
        description: | # this will include new lines to allow paragraphs
          - Researched on hardware & software level performance variations in HPC systems

          - Developed LSTM-based machine learning model to forecast time-series based performance metrics in HPC production systems
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boston University
        caption: 2018 - 2022
        sub_title: PhD Computer Engineering
        description: | # this will include new lines to allow paragraphs
          - GPA: 3.8

          - Coursework: Machine Learning, Deep Learning, Learning from Data, Fairness in AI, Advanced Data Structures
      - layout: left
        title: Sabanci University
        caption: 2013 - 2018
        sub_title: BSc Electronics Engineering
        description: | # this will include new lines to allow paragraphs
          - GPA: 3.9

          - High Honor(100%) Scholarship

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
